scriptencoding utf-8

" カラー設定:
colorscheme yama-dev
" どのモードでもマウスを使えるようにする
set mouse=a
" マウスの移動でフォーカスを自動的に切替えない (mousefocus:切替る)
set nomousefocus
" 起動時のウインドウサイズ
set columns=180
set lines=50
" コマンドラインの高さ
set cmdheight=3

" カーソルを行頭、行末で止まらないようにする
set whichwrap=b,s,h,l,<,>,[,]
set viminfo='20,f1,<500,s100,h,%
set viminfo+=n~/.vim/viminfo

" フォント設定
if has('win32')
  " for Windows
  set guifont=Ricty:h12:cSHIFTJIS
  " 行間隔の設定
  set linespace=-1
  if has('kaoriya')
    set ambiwidth=auto
  endif
elseif has('mac')
  set guifont=Osaka－等幅:h12
elseif has('xfontset')
  set guifontset=a14,r14,k14
endif
set renderoptions=type:directx
set antialias

" 日本語入力に関する設定:
if has('multi_byte_ime') || has('xim')
  " IME ON時のカーソルの色を設定
  highlight CursorIM guibg=Red guifg=NONE
  " 挿入モード・検索モードでのデフォルトのIME状態設定
  set iminsert=0 imsearch=0
  "inoremap <silent> <ESC> <ESC>:set iminsert=0<CR>
endif

" 透過の設定
if has('win32')
  " for Windows
  autocmd GUIEnter * set transparency=215
elseif has('mac')
  " for Mac
  set transparency=5
endif
