
[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  call deoplete#custom#option({
    \ 'auto_complete_delay': 200,
    \ 'smart_case': v:true,
    \ })
'''

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
build = '''
  npm install -g tern
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  colorscheme tender
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_leader_key='<C-e>'
  let g:user_emmet_settings={"variables":{"lang":"ja"}}
'''

[[plugins]]
repo = 'leftouterjoin/changed'

