# Util.
[[plugins]]
repo = 'equalsraf/neovim-gui-shim'
on_if = 'has("nvim")'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  set tags=tags;
  let g:tagbar_left = 0
  let g:tagbar_width = 60
  let g:tagbar_autoclose = 0
  let g:tagbar_autofocus = 0
  let g:tagbar_show_linenumbers = 1
  let g:tagbar_sort = 0
  let g:tagbar_type_javascript = {
  \  'ctagstype' : 'JavaScript',
  \  'kinds' : [
  \     'C:constants',
  \     'c:classes',
  \     'f:functions',
  \     'm:methods',
  \     'p:properties',
  \     'v:global variables',
  \     'g:generators'
  \  ]
  \}
  let g:tagbar_type_html = {
  \  'ctagstype' : 'Html',
  \  'kinds' : [
  \    'a:named anchors',
  \    'h:H1 headings',
  \    'i:H2 headings',
  \    'j:H3 headings'
  \  ]
  \}
  let g:tagbar_type_scss = {
  \  'ctagstype' : 'css',
  \  'kinds' : [
  \    'v:variables',
  \    'c:classes',
  \    'i:identities',
  \    't:tags',
  \    'm:medias'
  \  ]
  \}
  noremap <Space>l :Tagbar<CR>
'''

[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
  nnoremap U :UndotreeToggle<CR>
'''

# JSDoc
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
hook_add = '''
  let g:jsdoc_allow_input_prompt=1
  let g:jsdoc_input_description=1
  let g:jsdoc_enable_es6=1
  nnoremap <Space>j :JsDoc<CR>
'''

# toml.
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
hook_add = '''
  autocmd BufRead,BufNewFile,BufReadPre *.toml set filetype=toml
'''

# slim.
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']
hook_add = '''
  autocmd BufRead,BufNewFile *.slim setfiletype slim
'''

