# Util.
[[plugins]]
repo = 'equalsraf/neovim-gui-shim'
on_if = 'has("nvim")'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  set tags=tags;
  let g:tagbar_left = 0
  let g:tagbar_width = 60
  let g:tagbar_autoclose = 0
  let g:tagbar_autofocus = 0
  let g:tagbar_show_linenumbers = 1
  noremap <Space>l :Tagbar<CR>
'''

[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
  nnoremap U :UndotreeToggle<CR>
'''

# JSDoc
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
hook_add = '''
  let g:jsdoc_allow_input_prompt=1
  let g:jsdoc_input_description=1
  let g:jsdoc_enable_es6=1
  nnoremap <Space>j :JsDoc<CR>
'''

# toml.
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
hook_add = '''
  autocmd BufRead,BufNewFile,BufReadPre *.toml set filetype=toml
'''

# slim.
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'
hook_add = '''
  autocmd BufRead,BufNewFile *.slim setfiletype slim
'''

