# Util.
[[plugins]]
repo = 'equalsraf/neovim-gui-shim'
on_if = 'has("nvim")'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  set tags=tags;
  let g:tagbar_left = 0
  let g:tagbar_width = 60
  let g:tagbar_autoclose = 0
  let g:tagbar_autofocus = 0
  let g:tagbar_show_linenumbers = 1
  noremap <Space>l :Tagbar<CR>
'''

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']
hook_add = '''
  let g:closetag_filenames='*.html'
  let g:closetag_xhtml_filenames='*.jsx,*.tsx,*.vue'
  let g:closetag_filetypes='html'
  let g:closetag_xhtml_filetypes='jsx,tsx,javascript.jsx,typescript.tsx,vue'
  let g:closetag_emptyTags_caseSensitive=1
  let g:closetag_shortcut='>'
'''

[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
  nnoremap U :UndotreeToggle<CR>
'''

# JSDoc
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
hook_add = '''
  let g:jsdoc_allow_input_prompt=1
  let g:jsdoc_input_description=1
  let g:jsdoc_enable_es6=1
  nnoremap <Space>j :JsDoc<CR>
'''
